
[versions]
# Kotlin
kotlin = "2.1.21"
kotlinx-coroutines = "1.8.0"
kotlinx-serialization-json = "1.6.3"

#koin
koin = "4.0.4"

# Compose
compose = "1.8.2"
compose-compiler = "1.5.11" # Версия компилятора, совместимая с Kotlin 1.9.23/2.x.x

# Android
android-gradle-plugin = "8.2.2"
android-appcompat = "1.6.1"
android-core-ktx = "1.12.0"
android-activity-compose = "1.8.2"

# Ktor & Ollama
ktor = "3.1.3"
nirmato-ollama = "0.2.0"

[libraries]
# Coroutines
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

# Ktor
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

# Ktor (BOM импортирует все согласованные версии)
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-android = { module = "io.ktor:ktor-client-android" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp" } # Android-движок
ktor-client-cio = { module = "io.ktor:ktor-client-cio" }       # Desktop-движок
# Serialization
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
# Ollama Client
nirmato-ollama-client = { module = "org.nirmato.ollama:nirmato-ollama-client-ktor", version.ref = "nirmato-ollama" }
# AndroidX
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "android-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "android-core-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "android-activity-compose" }
androidx-material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }

[plugins]
# Плагины для блока `plugins` в build.gradle.kts
androidApplication = { id = "com.android.application", version.ref = "android-gradle-plugin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }